import assert from "node:assert/strict";
import fs from "node:fs";

const packageJson = JSON.parse(fs.readFileSync("package.json", "utf8"));
const manifest = JSON.parse(fs.readFileSync("manifest.json", "utf8"));
const versions = JSON.parse(fs.readFileSync("versions.json", "utf8"));
const readme = fs.readFileSync("README.md", "utf8");
const main = fs.readFileSync("src/main.ts", "utf8");
const gitStatus = fs.readFileSync("src/git-status.ts", "utf8");
const styles = fs.readFileSync("styles.css", "utf8");

assert.equal(packageJson.scripts.build, "NODE_ENV=production node esbuild.config.mjs");
assert.equal(packageJson.scripts.typecheck, "tsc --noEmit");
assert.equal(packageJson.scripts.lint, "node tests/lint.mjs");
assert.equal(manifest.id, "git-viewer");
assert.equal(manifest.isDesktopOnly, true);
assert.match(manifest.description, /history/i);
assert.match(manifest.description, /selected-file commits/i);
assert.match(manifest.version, /^\d+\.\d+\.\d+$/);
assert.equal(versions[manifest.version], manifest.minAppVersion);
assert.equal(readme.includes("Push current branch"), false);
assert.equal(readme.includes("read-only Git status"), false);
assert.match(gitStatus, /status", "--porcelain=v1", "-z", "--untracked-files=all"/);
assert.match(gitStatus, /"log", `--max-count=\$\{safeLimit\}`/);
assert.match(gitStatus, /"show", "--date=iso-strict"/);
assert.match(gitStatus, /parseGitLog/);
assert.match(gitStatus, /parseGitShow/);
assert.match(gitStatus, /formatGitCommandError/);
assert.match(gitStatus, /GIT_INDEX_FILE/);
assert.match(gitStatus, /commit-tree/);
assert.match(gitStatus, /reset", "-q", "--"/);
assert.match(main, /registerView/);
assert.match(main, /getRightLeaf/);
assert.match(main, /getAbstractFileByPath/);
assert.match(main, /getVisibleEntries/);
assert.match(main, /hidden or internal Git path/);
assert.match(main, /Select all/);
assert.match(main, /Unselect all/);
assert.match(main, /Commit selected/);
assert.match(main, /History/);
assert.match(main, /View in History/);
assert.match(main, /await this\.app\.workspace\.revealLeaf\(leaf\)/);
assert.match(readme, /- pull/);
assert.match(readme, /git log/);
assert.match(readme, /git show --name-status/);
assert.match(readme, /Commit selected files/);
assert.equal(main.includes("open-git-viewer"), false);
assert.equal(main.includes("refresh-git-viewer"), false);
assert.equal(main.includes("Open Git Viewer"), true);
assert.equal(main.includes("Refresh Git Viewer"), false);
assert.equal(main.includes("git push"), false);
assert.equal(main.includes("git pull"), false);
assert.equal(main.includes("git fetch"), false);
assert.equal(main.includes("git reset"), false);
assert.equal(gitStatus.includes('"push"'), false);
assert.equal(gitStatus.includes('"pull"'), false);
assert.equal(gitStatus.includes('"fetch"'), false);
assert.equal(styles.includes("!important"), false);

console.log("Git Viewer lint checks passed.");
